---
title: "Investigate TMA exhaustion markers"
author: "Christelle Colin-Leitzinger"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: united
    highlight: pygments
    df_print: paged
editor_options: 
  chunk_output_type: console
---

<style type="text/css">

.figure {
   margin-top: 25px;
   margin-bottom: 100px;
}

table {
    margin-top: 10px;
    margin-bottom: 25px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      fig.align='center'
                      )
```

```{r library, echo = FALSE}
library(tidyverse)
library(gtsummary)
theme_gtsummary_compact()
theme_set(theme_classic())
```

```{r load}
TMA_exhaustion2024 <- read_rds(paste0(here::here(), "/raw_data_all_TMAs_exhaustion_panel_2024.rds"))
tma_panel1 <- read_rds(paste0(here::here(), "/markers_AACES_NCOCS_batch1_2_07132023.rds"))
```

# Abundance Tumor/Stroma cells over batches
```{r}
TMA_exhaustion2024 %>% 
  mutate(tumor_total_cells = tumor_total_cells / total_cells * 100) %>% 
  mutate(stroma_total_cells = stroma_total_cells / total_cells * 100) %>% 
  select(aaces_phase, tumor_total_cells, stroma_total_cells) %>% 
  pivot_longer(cols = -aaces_phase) %>% 
  ggplot(aes(x = aaces_phase, y = value))+
  geom_violin()+
  labs(y = "Perecent of cells (%)")+
  facet_wrap(.~ name)

TMA_exhaustion2024 %>% 
  mutate(tumor_total_cells = tumor_total_cells / total_cells * 100) %>% 
  mutate(stroma_total_cells = stroma_total_cells / total_cells * 100) %>% 
  select(tma_batch, tumor_total_cells, stroma_total_cells) %>% 
  pivot_longer(cols = -tma_batch) %>% 
  ggplot(aes(x = tma_batch, y = value))+
  geom_violin()+
  labs(y = "Perecent of cells (%)")+
  facet_wrap(.~ name)
```

# Focus on 2017 / 2018 data
2017 121 patients included. 1 excluded (core not intact).    
2018 34 patients.  
```{r}
TMA_exhaustion2024 <- TMA_exhaustion2024 %>% 
  filter(tma_batch != "tma 2024")
```


```{r}
TMA_exhaustion2024 %>% 
  select(tma_batch, starts_with("tumor_percent_"),
         starts_with("stroma_percent_"),
         starts_with("total_percent_")) %>% 
  pivot_longer(cols = -tma_batch) %>% 
  mutate(compartment = str_match(name, "(.*)_percent_(.*)_positive_cells")[,2]) %>% 
  mutate(marker = str_match(name, "(.*)_percent_(.*)_positive_cells")[,3],
         marker = str_remove(marker, "_opal_.*"),
         marker = str_replace_all(marker, "plus", "+"),
         marker = str_replace_all(marker, "minus", "-"),
         marker = str_remove_all(marker, "_")) %>% 
  ggplot(aes(x = marker, y = value))+
  geom_violin()+
  labs(y = "Perecent of cells (%)")+
  facet_wrap(.~ compartment, ncol = 1)+
  coord_flip()

TMA_exhaustion2024 %>% 
  select(tma_batch, tumor_percent_cd3_opal_690_positive_cells,
         total_percent_cd3_opal_690_positive_cells,
         stroma_percent_cd3_opal_690_positive_cells) %>% 
  pivot_longer(cols = -tma_batch) %>% 
  mutate(compartment = str_match(name, "(.*)_percent_(.*)_positive_cells")[,2]) %>% 
  mutate(marker = str_match(name, "(.*)_percent_(.*)_positive_cells")[,3],
         marker = str_remove(marker, "_opal_.*"),
         marker = str_replace_all(marker, "plus", "+"),
         marker = str_replace_all(marker, "minus", "-"),
         marker = str_remove_all(marker, "_")) %>% 
  ggplot(aes(x = marker, y = value))+
  geom_violin()+
  labs(y = "Perecent of cells (%)")+
  ylim(0,90)+
  facet_wrap(.~ compartment, ncol = 3)

TMA_exhaustion2024 %>% 
  select(tma_batch, tumor_percent_cd3plus_cd8plus_positive_cells,
         total_percent_cd3plus_cd8plus_positive_cells,
         stroma_percent_cd3plus_cd8plus_positive_cells) %>% 
  pivot_longer(cols = -tma_batch) %>% 
  mutate(compartment = str_match(name, "(.*)_percent_(.*)_positive_cells")[,2]) %>% 
  mutate(marker = str_match(name, "(.*)_percent_(.*)_positive_cells")[,3],
         marker = str_remove(marker, "_opal_.*"),
         marker = str_replace_all(marker, "plus", "+"),
         marker = str_replace_all(marker, "minus", "-"),
         marker = str_remove_all(marker, "_")) %>% 
  ggplot(aes(x = marker, y = value))+
  geom_boxplot()+
  labs(y = "Perecent of cells (%)")+
  ylim(0,35)+
  facet_wrap(.~ compartment, ncol = 3)

TMA_exhaustion2024 %>% 
  select(tma_batch, starts_with("tumor_percent_"),
         starts_with("stroma_percent_"),
         starts_with("total_percent_")) %>% 
  pivot_longer(cols = -tma_batch) %>% 
  mutate(compartment = str_match(name, "(.*)_percent_(.*)_positive_cells")[,2]) %>% 
  mutate(marker = str_match(name, "(.*)_percent_(.*)_positive_cells")[,3],
         marker = str_remove(marker, "_opal_.*"),
         marker = str_replace_all(marker, "plus", "+"),
         marker = str_replace_all(marker, "minus", "-"),
         marker = str_remove_all(marker, "_")) %>% 
  ggplot(aes(x = marker, y = value))+
  geom_violin()+
  labs(y = "Perecent of cells (%)")+
  ylim(0, 0.05)+
  facet_wrap(.~ compartment, ncol = 1)+
  coord_flip()
```

```{r}
TMA_exhaustion2024 %>% 
  select(tma_batch, starts_with("tumor_percent_")) %>% 
  `colnames<-`(c(colnames(.) %>% 
                   str_remove_all(., "_opal_.*|percent_|_positive_cells*") %>% 
                   str_replace_all(., "plus", "+") %>% 
                   str_replace_all(., "minus", "-")
                 )) %>% 
  tbl_summary(by = tma_batch,
              type = everything() ~ "continuous",
              statistic = list(all_continuous() ~ "{mean} ({sd})"),
              # label = list(percent_CD3_tumor ~ "percent CD3+", percent_CD3_CD8_tumor ~ "percent CD3+/CD8+",
              #              percent_CD3_FoxP3_tumor ~ "percent CD3+/FoxP3+",
              #              percent_CD11b_tumor ~ "percent CD11b+", percent_CD11b_CD15_tumor ~ "percent CD11b+/CD15+"),
              missing = "no", digits = list(all_continuous() ~ 2)) %>% 
  bold_labels() %>% 
  add_overall()

TMA_exhaustion2024 %>% 
  select(tma_batch, starts_with("stroma_percent_")) %>% 
  `colnames<-`(c(colnames(.) %>% 
                   str_remove_all(., "_opal_.*|percent_|_positive_cells*") %>% 
                   str_replace_all(., "plus", "+") %>% 
                   str_replace_all(., "minus", "-")
                 )) %>% 
  tbl_summary(by = tma_batch,
              type = everything() ~ "continuous",
              # statistic = list(all_continuous() ~ "{mean} ({sd})"),
              # label = list(percent_CD3_tumor ~ "percent CD3+", percent_CD3_CD8_tumor ~ "percent CD3+/CD8+",
              #              percent_CD3_FoxP3_tumor ~ "percent CD3+/FoxP3+",
              #              percent_CD11b_tumor ~ "percent CD11b+", percent_CD11b_CD15_tumor ~ "percent CD11b+/CD15+"),
              missing = "no", digits = list(all_continuous() ~ 2)) %>% 
  bold_labels() %>% 
  add_overall()

TMA_exhaustion2024 %>% 
  select(tma_batch, starts_with("total_percent_")) %>% 
  `colnames<-`(c(colnames(.) %>% 
                   str_remove_all(., "_opal_.*|percent_|_positive_cells*") %>% 
                   str_replace_all(., "plus", "+") %>% 
                   str_replace_all(., "minus", "-")
                 )) %>% 
  tbl_summary(by = tma_batch,
              type = everything() ~ "continuous",
              # statistic = list(all_continuous() ~ "{mean} ({sd})"),
              # label = list(percent_CD3_tumor ~ "percent CD3+", percent_CD3_CD8_tumor ~ "percent CD3+/CD8+",
              #              percent_CD3_FoxP3_tumor ~ "percent CD3+/FoxP3+",
              #              percent_CD11b_tumor ~ "percent CD11b+", percent_CD11b_CD15_tumor ~ "percent CD11b+/CD15+"),
              missing = "no", digits = list(all_continuous() ~ 2)) %>% 
  bold_labels() %>% 
  add_overall()

```

```{r}

```




# Averaged
```{r}
TMA_exhaustion2024 %>% 
  group_by(suid) %>% 
  summarize(
    mean_tumor = mean(percent_tumor),
    mean_stroma = mean(percent_stroma),
    mean_total = mean(percent_total),
    # variance_tumor = var(percent_tumor),
    # variance_stroma = var(percent_stroma),
    percent_CD3_tumor = mean(tumor_percent_cd3_opal_650_positive_cells),
    percent_CD8_tumor = mean(tumor_percent_cd8_opal_570_positive_cells)
  )
```





















